forge "https://forgeapi.puppetlabs.com"

mod 'example42-iptables'
mod 'garethr-docker'
mod 'puppetlabs-ntp'
mod 'rtyler/jenkins'
mod 'tracywebtech-pip'

mod 'puppetlabs-apache', '1.1.1'
mod 'puppetlabs-vcsrepo'
