forge "https://forgeapi.puppetlabs.com"

mod 'example42-iptables'
mod 'garethr-docker'
mod 'puppetlabs-ntp'
mod 'rtyler/jenkins'
mod 'tracywebtech-pip', '1.3.2'
mod 'newrelic-nrsysmond',
  :git => "git://github.com/newrelic/puppet-nrsysmond.git"

mod 'saz-timezone'
