forge "https://forgeapi.puppetlabs.com"

mod 'example42-iptables'
mod 'garethr-docker', '5.0.0'
mod 'puppetlabs-apache', '1.1.1'
mod 'puppetlabs-concat', '1.2.3'
mod 'puppetlabs-ntp'
mod 'rtyler/jenkins'
mod 'tracywebtech-pip', '1.3.2'
mod 'newrelic-nrsysmond',
  :git => "git://github.com/newrelic/puppet-nrsysmond.git"

mod 'saz-timezone'
