name         'krakatoa-upstart'
version      '0.0.1'
source       ''
author       'DevOps Team Oasiswork'
license      'Apache License, Version 2.0'
summary      'Puppet Upstart module'
description  'This module manages Upstart job configurations.
Forked from https://github.com/bison/puppet-upstart'
project_page ''

dependency 'puppetlabs/stdlib', '>= 0.1.6'
