forge "https://forgeapi.puppetlabs.com"

mod 'garethr-docker'
mod 'krakatoa-upstart'
mod 'puppetlabs-ntp'
mod 'rtyler/jenkins'
mod 'tracywebtech-pip'
mod 'newrelic-nrsysmond',
  :git => "git://github.com/newrelic/puppet-nrsysmond.git"
