forge "https://forgeapi.puppetlabs.com"

mod 'garethr-docker', '5.0.0'
mod 'krakatoa-upstart', :path => '../krakatoa-upstart-0.0.1'
mod 'puppetlabs-concat', '1.2.3'
mod 'puppetlabs-ntp', '4.2.0'
mod 'rtyler/jenkins', '1.6.1'
mod 'tracywebtech-pip', '1.3.2'
mod 'newrelic-nrsysmond',
  :git => "git://github.com/newrelic/puppet-nrsysmond.git"
